### ISSUE TITLE
Pasting JMH clipboard output does not show correctly

### ISSUE THREAD

**Issue by NiinS** [akarnokd/jmh-compare-gui#9]
Hi,

When I pasted the following JMH output to the GUI, the columns were not showing correctly.

![image](https://cloud.githubusercontent.com/assets/3360301/21480289/67025eb8-cb53-11e6-8c06-641ce5c8d794.png)

So the text I copied and pasted was:

```
Benchmark                                                      Mode  Cnt   Score                      Error                    Units
RxFlatmapVersusDeferBenchmark.helloWorld   thrpt   200   2191821684.391    ± 37772457.512   ops/s
```
 

The resulting screen was:

![image](https://cloud.githubusercontent.com/assets/3360301/21480317/a9bdcabc-cb53-11e6-9da4-c33a9eeb4394.png)

Can you please suggest if I'm doing it incorrectly? Why are some columns not shown with a name and why the error column is showing "null". How can see an output similar to illustrated screen on Github project page.

My JMH version is:  1.17.3

**Comment by akarnokd** [comment]
Pasted columns have no name. Right click on a row below the column and pick rename.

**Comment by NiinS** [comment]
Thanks. That was helpful.
